[[redirects]]
  from = "/api/*"
  to = "http://3.106.141.19/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media/*"
  to = "http://3.106.141.19/media/:splat"
  status = 200
  force = true